### ISSUE TITLE
let's make a button!

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-standards#10]
In the interest of getting links to this repo as visibly added to our other repos, it might be cool to make a little button graphic that we can add to README.md files that says something along the lines of "this repo conforms to superawesometown mofo guidelines" and links back here when clicked.

**Comment by mmmavis** [comment]
seems like this is done? 💃 

[![Uses Mofo Standards](https://MozillaFoundation.github.io/mofo-standards/badge.svg)](https://github.com/MozillaFoundation/mofo-standards)

**Comment by Pomax** [comment]
yups!
