### ISSUE TITLE
Standardize on `shx`

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/mofo-standards#6]
[shx](https://github.com/shelljs/shx) is essentially a CLI wrapper for [ShellJS](http://documentup.com/shelljs/shelljs). It makes setting up x-platform compatible npm scripts very easy (mostly just prefix standard unix commands w. "shx").

EG:

`shx mkdir foo` will work anywhere Node runs, not just on UNIX systems.

Currently we use a whole plethora of single purpose Node modules (eg: `rimraf`, `mkdirp`), but this is a nice all-in-one solution. Less dependencies FTW!

**Comment by gvn** [comment]
CC: @Pomax

**Comment by Pomax** [comment]
updoot - removing explicit dependencies is great.

**Comment by gvn** [comment]
Sounds like everyone is on board
